services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: omnichat
      POSTGRES_PASSWORD: omnichatpass
      POSTGRES_DB: omnichatdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
